import type { Product, Character, Collection } from "./types"

export const featuredProducts: Product[] = [
  {
    id: "1",
    name: "Pushpa Raj Red Floral Shirt",
    description: "Inspired by Allu Arjun's iconic look in Pushpa: The Rise",
    price: 1299,
    image: "/images/products/pushpa-raj-red-floral-shirt.jpg",
    character: "Pushpa Raj",
    movie: "Pushpa",
    affiliateLink:
      "https://thebearhouse.com/products/maximus?pr_prod_strat=e5_desc&pr_rec_id=6cd772486&pr_rec_pid=8915767623931&pr_ref_pid=8915762643195&pr_seq=uniform",
    category: "Shirts",
    gender: "Men",
    style: "Rugged",
  },
  {
    id: "2",
    name: "Maharshi Urban Casual Jacket",
    description: "Sleek jacket inspired by Mahesh Babu's style in Maharshi",
    price: 2499,
    image: "/placeholder.svg?height=500&width=400",
    character: "Rishi",
    movie: "Maharshi",
    affiliateLink: "https://vanheusenindia.abfrl.in/p/van-heusen-red-shirt-800335.html",
    category: "Jackets",
    gender: "Men",
    style: "Urban",
  },
  {
    id: "3",
    name: "Sita Floral Saree",
    description: "Elegant saree inspired by Samantha's look in Seethamma Vakitlo Sirimalle Chettu",
    price: 3999,
    image: "/placeholder.svg?height=500&width=400",
    character: "Seetha",
    movie: "Seethamma Vakitlo Sirimalle Chettu",
    affiliateLink: "https://example.com/product3",
    category: "Sarees",
    gender: "Women",
    style: "Traditional",
  },
  {
    id: "4",
    name: "Baahubali Royal Kurta Set",
    description: "Regal kurta set inspired by Prabhas in Baahubali",
    price: 2999,
    image: "/images/characters/prabhas-baahubali.jpg",
    character: "Amarendra Baahubali",
    movie: "Baahubali",
    affiliateLink:
      "https://www.amazon.in/BookMyCostume-Baahubali-Warrior-Character-Costume/dp/B08KT949QL/ref=sr_1_8?sr=8-8",
    category: "Kurtas",
    gender: "Men",
    style: "Royal",
  },
  {
    id: "5",
    name: "RRR Komaram Bheem Dhoti Set",
    description: "Traditional dhoti set inspired by NTR Jr's look in RRR",
    price: 719,
    image: "/images/characters/ntr-rrr.jpg",
    character: "Komaram Bheem",
    movie: "RRR",
    affiliateLink:
      "https://www.myntra.com/kurtas/molly+%26+michel/molly--michel-men-black-solid-pathani-kurta/10140265/buy?storeContext=fwd",
    category: "Traditional",
    gender: "Men",
    style: "Tribal",
  },
  {
    id: "6",
    name: "Arjun Reddy Casual Outfit",
    description: "Casual outfit inspired by Vijay Deverakonda in Arjun Reddy",
    price: 2199,
    image: "/images/characters/vijay-deverakonda-arjun-reddy-hd.jpg",
    character: "Arjun Reddy",
    movie: "Arjun Reddy",
    affiliateLink: "https://www.meesho.com/grey-plain-shirt-for-men/p/76o7wp",
    category: "Casual",
    gender: "Men",
    style: "Urban",
  },
  {
    id: "7",
    name: "Fidaa Traditional Anarkali",
    description: "Beautiful anarkali inspired by Sai Pallavi in Fidaa",
    price: 3499,
    image: "/images/characters/sai-pallavi-fidaa.jpg",
    character: "Bhanumathi",
    movie: "Fidaa",
    affiliateLink: "https://example.com/product7",
    category: "Anarkali",
    gender: "Women",
    style: "Traditional",
  },
  {
    id: "8",
    name: "Rangasthalam Period Outfit",
    description: "Vintage-inspired outfit from Ram Charan's look in Rangasthalam",
    price: 1799,
    image: "/images/characters/ram-charan-rangasthalam.jpg",
    character: "Chitti Babu",
    movie: "Rangasthalam",
    affiliateLink:
      "https://www.flipkart.com/gowri-tex-checkered-multicolor-lungi/p/itm37bdaa48a36f5?pid=LNGH3ZWHHZV4AY4Z&lid=LSTLNGH3ZWHHZV4AY4ZMCYWY9&marketplace=FLIPKART&store=clo%2Fvua%2F5jo%2Fcqs&spotlightTagId=default_TrendingId_clo%2Fvua%2F5jo%2Fcqs&srno=b_1_3&otracker=browse&fm=organic&iid=d76d9a63-5163-4db8-be85-bc1e28a1383e.LNGH3ZWHHZV4AY4Z.SEARCH&ppt=browse&ppn=browse&ssid=8o6qux4g0w0000001749100650375",
    category: "Period",
    gender: "Men",
    style: "Vintage",
  },
  {
    id: "9",
    name: "Pokiri Leather Jacket",
    description: "Edgy leather jacket inspired by Mahesh Babu's iconic look in Pokiri",
    price: 3299,
    image: "/placeholder.svg?height=500&width=400",
    character: "Pandu",
    movie: "Pokiri",
    affiliateLink: "https://example.com/product9",
    category: "Jackets",
    gender: "Men",
    style: "Rugged",
  },
  {
    id: "10",
    name: "Jalsa Casual Shirt Set",
    description: "Stylish casual shirt inspired by Pawan Kalyan's look in Jalsa",
    price: 1599,
    image: "/placeholder.svg?height=500&width=400",
    character: "Sanjay Sahu",
    movie: "Jalsa",
    affiliateLink: "https://example.com/product10",
    category: "Shirts",
    gender: "Men",
    style: "Casual",
  },
  {
    id: "11",
    name: "Darling Denim Collection",
    description: "Trendy denim outfit inspired by Prabhas in Darling",
    price: 2499,
    image: "/placeholder.svg?height=500&width=400",
    character: "Prabha",
    movie: "Darling",
    affiliateLink: "https://example.com/product11",
    category: "Denim",
    gender: "Men",
    style: "Casual",
  },
  {
    id: "12",
    name: "Bommarillu College Look",
    description: "Youthful college outfit inspired by Siddharth in Bommarillu",
    price: 1799,
    image: "/placeholder.svg?height=500&width=400",
    character: "Siddhu",
    movie: "Bommarillu",
    affiliateLink: "https://example.com/product12",
    category: "Casual",
    gender: "Men",
    style: "College",
  },
  {
    id: "13",
    name: "Athadu Formal Shirt",
    description: "Sophisticated formal shirt inspired by Mahesh Babu in Athadu",
    price: 1899,
    image: "/placeholder.svg?height=500&width=400",
    character: "Nandu",
    movie: "Athadu",
    affiliateLink: "https://example.com/product13",
    category: "Formal",
    gender: "Men",
    style: "Sophisticated",
  },
  {
    id: "14",
    name: "Oosaravelli Printed Shirt",
    description: "Bold printed shirt inspired by NTR's unique style in Oosaravelli",
    price: 1699,
    image: "/placeholder.svg?height=500&width=400",
    character: "Tony",
    movie: "Oosaravelli",
    affiliateLink: "https://example.com/product14",
    category: "Shirts",
    gender: "Men",
    style: "Bold",
  },
  {
    id: "15",
    name: "Seethamma Vakitlo Traditional Saree",
    description: "Elegant traditional saree inspired by Samantha in Seethamma Vakitlo Sirimalle Chettu",
    price: 4599,
    image: "/placeholder.svg?height=500&width=400",
    character: "Seetha",
    movie: "Seethamma Vakitlo Sirimalle Chettu",
    affiliateLink:
      "https://www.flipkart.com/yogeshwar-designer-women-kurti-pant-dupatta-set/p/itm3e884bb042f24?pid=ETHH2DFFESF8Z3HB&lid=LSTETHH2DFFESF8Z3HB1S1IKP&marketplace=FLIPKART&cmpid=content_ethnic-set_8965229628_gmc",
    category: "Sarees",
    gender: "Women",
    style: "Traditional",
  },
  {
    id: "16",
    name: "Race Gurram Party Outfit",
    description: "Stylish party wear inspired by Allu Arjun in Race Gurram",
    price: 2899,
    image: "/placeholder.svg?height=500&width=400",
    character: "Lucky",
    movie: "Race Gurram",
    affiliateLink: "https://example.com/product16",
    category: "Party Wear",
    gender: "Men",
    style: "Trendy",
  },
  {
    id: "17",
    name: "Magadheera Royal Outfit",
    description: "Regal period costume inspired by Ram Charan in Magadheera",
    price: 5299,
    image: "/placeholder.svg?height=500&width=400",
    character: "Kala Bhairava",
    movie: "Magadheera",
    affiliateLink: "https://example.com/product17",
    category: "Period",
    gender: "Men",
    style: "Royal",
  },
  {
    id: "18",
    name: "Geetha Govindam Casual Set",
    description: "Charming casual outfit inspired by Vijay Deverakonda in Geetha Govindam",
    price: 1999,
    image: "/placeholder.svg?height=500&width=400",
    character: "Vijay Govind",
    movie: "Geetha Govindam",
    affiliateLink: "https://example.com/product18",
    category: "Casual",
    gender: "Men",
    style: "Charming",
  },
  {
    id: "19",
    name: "Sita Ramam Vintage Dress",
    description: "Elegant vintage dress inspired by Mrunal Thakur in Sita Ramam",
    price: 3799,
    image: "/images/characters/mrunal-thakur-sita-ramam-new.jpg",
    character: "Sita Mahalakshmi",
    movie: "Sita Ramam",
    affiliateLink: "https://cinderellacloset.in/products/2615",
    category: "Dresses",
    gender: "Women",
    style: "Vintage",
  },
  {
    id: "20",
    name: "Taxiwaala Leather Jacket",
    description: "Stylish leather jacket inspired by Vijay Deverakonda in Taxiwaala",
    price: 2999,
    image: "/placeholder.svg?height=500&width=400",
    character: "Shiva",
    movie: "Taxiwaala",
    affiliateLink: "https://example.com/product20",
    category: "Jackets",
    gender: "Men",
    style: "Urban",
  },
  {
    id: "21",
    name: "RRR Komaram Bheem Blue Shirt",
    description: "Navy blue workwear shirt inspired by NTR Jr's iconic look in RRR",
    price: 1499,
    image: "/images/characters/ntr-rrr.jpg",
    character: "Komaram Bheem",
    movie: "RRR",
    affiliateLink: "https://example.com/product21",
    category: "Shirts",
    gender: "Men",
    style: "Tribal",
  },
  {
    id: "22",
    name: "RRR Leather Shoulder Strap",
    description: "Authentic leather accessory inspired by Komaram Bheem's costume in RRR",
    price: 2299,
    image: "/images/characters/ntr-rrr.jpg",
    character: "Komaram Bheem",
    movie: "RRR",
    affiliateLink: "https://example.com/product22",
    category: "Accessories",
    gender: "Men",
    style: "Tribal",
  },
  {
    id: "23",
    name: "Pushpa Raj Embroidered Red Shirt",
    description: "Iconic burgundy shirt with embroidery inspired by Allu Arjun in Pushpa",
    price: 1899,
    image: "/images/products/pushpa-raj-red-floral-shirt.jpg",
    character: "Pushpa Raj",
    movie: "Pushpa",
    affiliateLink: "https://example.com/product23",
    category: "Shirts",
    gender: "Men",
    style: "Rugged",
  },
  {
    id: "24",
    name: "Pushpa Gold Chain Set",
    description: "Layered gold chains inspired by Pushpa Raj's iconic look",
    price: 2499,
    image: "/images/products/pushpa-raj-red-floral-shirt.jpg",
    character: "Pushpa Raj",
    movie: "Pushpa",
    affiliateLink: "https://example.com/product24",
    category: "Accessories",
    gender: "Men",
    style: "Rugged",
  },
  {
    id: "25",
    name: "Baahubali Royal Armor Vest",
    description: "Majestic black armor vest with ornate details inspired by Amarendra Baahubali",
    price: 3999,
    image: "/images/characters/prabhas-baahubali.jpg",
    character: "Amarendra Baahubali",
    movie: "Baahubali",
    affiliateLink:
      "https://www.amazon.in/BookMyCostume-Baahubali-Warrior-Character-Costume/dp/B08KT949QL/ref=sr_1_8?sr=8-8",
    category: "Traditional",
    gender: "Men",
    style: "Royal",
  },
  {
    id: "26",
    name: "Baahubali Gold Jewelry Set",
    description: "Heavy traditional gold necklaces inspired by Baahubali's royal accessories",
    price: 5999,
    image: "/images/characters/prabhas-baahubali.jpg",
    character: "Amarendra Baahubali",
    movie: "Baahubali",
    affiliateLink:
      "https://www.amazon.in/BookMyCostume-Baahubali-Warrior-Character-Costume/dp/B08KT949QL/ref=sr_1_8?sr=8-8",
    category: "Accessories",
    gender: "Men",
    style: "Royal",
  },
  {
    id: "27",
    name: "Sita Ramam Teal Saree",
    description: "Elegant teal saree with intricate embroidery inspired by Mrunal Thakur in Sita Ramam",
    price: 4299,
    image: "/images/characters/mrunal-thakur-sita-ramam-new.jpg",
    character: "Sita Mahalakshmi",
    movie: "Sita Ramam",
    affiliateLink: "https://cinderellacloset.in/products/2615",
    category: "Sarees",
    gender: "Women",
    style: "Vintage",
  },
  {
    id: "28",
    name: "Sita Ramam Vintage Jewelry Set",
    description: "Classic 1960s-inspired jewelry set with traditional earrings and accessories",
    price: 1899,
    image: "/images/characters/mrunal-thakur-sita-ramam-new.jpg",
    character: "Sita Mahalakshmi",
    movie: "Sita Ramam",
    affiliateLink: "https://cinderellacloset.in/products/2615",
    category: "Accessories",
    gender: "Women",
    style: "Vintage",
  },
  {
    id: "29",
    name: "Sita Ramam Elegant Pink Saree",
    description: "Beautiful pink saree with golden border inspired by Mrunal Thakur's romantic look in Sita Ramam",
    price: 3599,
    image: "/images/characters/mrunal-thakur-sita-ramam-new.jpg",
    character: "Sita Mahalakshmi",
    movie: "Sita Ramam",
    affiliateLink: "https://cinderellacloset.in/products/2615",
    category: "Sarees",
    gender: "Women",
    style: "Vintage",
  },
  {
    id: "30",
    name: "Mirchi Formal Dress",
    description: "Elegant formal dress inspired by Prabhas's sophisticated look in Mirchi",
    price: 1099,
    image: "/images/characters/prabhas-mirchi.jpg",
    character: "Jai",
    movie: "Mirchi",
    affiliateLink:
      "https://www.amazon.in/Allen-Solly-Geometric-Regular-ASSFWMOFO48848_White_40/dp/B07DMQRD6H/ref=sr_1_10?sr=8-10&psc=1",
    category: "Formal",
    gender: "Men",
    style: "Sophisticated",
  },
]

export const spotlightCharacters: Character[] = [
  {
    id: "1",
    name: "Pushpa Raj",
    movie: "Pushpa: The Rise",
    actor: "Allu Arjun",
    image: "/images/products/pushpa-raj-red-floral-shirt.jpg",
    description:
      "The rugged, raw style of Pushpa Raj features bold prints, earthy tones, and a distinctive attitude that made this look iconic across India.",
    style: "Rugged & Raw",
    lookTags: ["Embroidered Shirts", "Rugged", "Earthy Tones", "Bearded Look", "Gold Accessories"],
  },
  {
    id: "2",
    name: "Amarendra Baahubali",
    movie: "Baahubali",
    actor: "Prabhas",
    image: "/images/characters/prabhas-baahubali.jpg",
    description:
      "The majestic royal attire of Amarendra Baahubali combines traditional elements with warrior aesthetics, creating a timeless regal look.",
    style: "Royal & Majestic",
    lookTags: ["Royal Armor", "Warrior", "Traditional Jewelry", "Regal", "Ornate Details"],
  },
  {
    id: "3",
    name: "Sita Mahalakshmi",
    movie: "Sita Ramam",
    actor: "Mrunal Thakur",
    image: "/images/characters/mrunal-thakur-sita-ramam-new.jpg",
    description:
      "The elegant vintage style of Sita Mahalakshmi features classic 1960s silhouettes, rich colors, and timeless accessories that evoke a romantic bygone era.",
    style: "Vintage & Elegant",
    lookTags: ["Vintage Sarees", "1960s Fashion", "Classic Jewelry", "Period Romance", "Elegant"],
  },
  {
    id: "4",
    name: "Arjun Reddy",
    movie: "Arjun Reddy",
    actor: "Vijay Deverakonda",
    image: "/images/characters/vijay-deverakonda-arjun-reddy-hd.jpg",
    description:
      "The rebellious, casual style of Arjun Reddy features dark colors, loose fits, and a signature beard that created a fashion trend among youth.",
    style: "Urban & Rebellious",
    lookTags: ["Casual", "Dark Colors", "Bearded Look", "Urban"],
  },
  {
    id: "5",
    name: "Pandu",
    movie: "Pokiri",
    actor: "Mahesh Babu",
    image: "/placeholder.svg?height=600&width=400",
    description:
      "The edgy, street-smart style of Pandu combines leather jackets, fitted tees, and an attitude that defined a generation of fashion-forward youth.",
    style: "Edgy & Street-smart",
    lookTags: ["Leather Jackets", "Fitted Tees", "Urban", "Rugged"],
  },
  {
    id: "6",
    name: "Sanjay Sahu",
    movie: "Jalsa",
    actor: "Pawan Kalyan",
    image: "/placeholder.svg?height=600&width=400",
    description:
      "The effortlessly cool style of Sanjay Sahu features casual shirts, relaxed fits, and a carefree attitude that resonated with fans across the country.",
    style: "Casual & Cool",
    lookTags: ["Casual Shirts", "Relaxed Fit", "Effortless", "Trendy"],
  },
  {
    id: "7",
    name: "Prabha",
    movie: "Darling",
    actor: "Prabhas",
    image: "/placeholder.svg?height=600&width=400",
    description:
      "The charming, boy-next-door style of Prabha features denim, casual tees, and a lovable persona that made this look widely imitated.",
    style: "Charming & Casual",
    lookTags: ["Denim", "Casual Tees", "Boy-next-door", "Approachable"],
  },
  {
    id: "8",
    name: "Siddhu",
    movie: "Bommarillu",
    actor: "Siddharth",
    image: "/images/characters/siddharth-bommarillu-hd.jpg",
    description:
      "The youthful, college-going style of Siddhu features bright colors, casual wear, and a fresh approach that appealed to the younger audience.",
    style: "Youthful & Fresh",
    lookTags: ["College Wear", "Bright Colors", "Casual", "Youthful"],
  },
  {
    id: "9",
    name: "Nandu",
    movie: "Athadu",
    actor: "Mahesh Babu",
    image: "/placeholder.svg?height=600&width=400",
    description:
      "The sophisticated, mysterious style of Nandu features formal shirts, structured outfits, and a composed demeanor that exudes class and elegance.",
    style: "Sophisticated & Mysterious",
    lookTags: ["Formal Shirts", "Structured", "Elegant", "Composed"],
  },
  {
    id: "10",
    name: "Tony",
    movie: "Oosaravelli",
    actor: "NTR",
    image: "/placeholder.svg?height=600&width=400",
    description:
      "The bold, eccentric style of Tony features printed shirts, unique accessories, and a distinctive look that stands out in any crowd.",
    style: "Bold & Eccentric",
    lookTags: ["Printed Shirts", "Unique Accessories", "Distinctive", "Colorful"],
  },
  {
    id: "11",
    name: "Seetha",
    movie: "Seethamma Vakitlo Sirimalle Chettu",
    actor: "Samantha",
    image: "/placeholder.svg?height=600&width=400",
    description:
      "The traditional, graceful style of Seetha features elegant sarees, simple jewelry, and a natural beauty that celebrates Telugu cultural aesthetics.",
    style: "Traditional & Graceful",
    lookTags: ["Sarees", "Simple Jewelry", "Natural", "Cultural"],
  },
  {
    id: "12",
    name: "Lucky",
    movie: "Race Gurram",
    actor: "Allu Arjun",
    image: "/placeholder.svg?height=600&width=400",
    description:
      "The trendy, party-ready style of Lucky features stylish outfits, fashionable accessories, and a confident attitude that makes a statement.",
    style: "Trendy & Stylish",
    lookTags: ["Party Wear", "Fashionable", "Confident", "Statement"],
  },
  {
    id: "13",
    name: "Kala Bhairava",
    movie: "Magadheera",
    actor: "Ram Charan",
    image: "/placeholder.svg?height=600&width=400",
    description:
      "The regal, period-inspired style of Kala Bhairava features ornate costumes, traditional jewelry, and a majestic presence that transports you to another era.",
    style: "Regal & Period",
    lookTags: ["Royal", "Period Costume", "Ornate", "Traditional"],
  },
  {
    id: "14",
    name: "Vijay Govind",
    movie: "Geetha Govindam",
    actor: "Vijay Deverakonda",
    image: "/placeholder.svg?height=600&width=400",
    description:
      "The charming, boy-next-door style of Vijay Govind features casual shirts, comfortable pants, and an approachable look that resonated with young audiences.",
    style: "Charming & Approachable",
    lookTags: ["Casual Shirts", "Comfortable", "Approachable", "Simple"],
  },
  {
    id: "15",
    name: "Shiva",
    movie: "Taxiwaala",
    actor: "Vijay Deverakonda",
    image: "/placeholder.svg?height=600&width=400",
    description:
      "The urban, street-style look of Shiva features leather jackets, casual tees, and a rugged appeal that created a distinctive fashion statement.",
    style: "Urban & Street",
    lookTags: ["Leather Jackets", "Casual Tees", "Rugged", "Street Style"],
  },
  {
    id: "16",
    name: "Rishi",
    movie: "Maharshi",
    actor: "Mahesh Babu",
    image: "/placeholder.svg?height=600&width=400",
    description:
      "The corporate-to-casual transformation of Rishi features both sleek business attire and relaxed rural looks, showcasing versatility in style.",
    style: "Corporate & Versatile",
    lookTags: ["Business Attire", "Casual Transformation", "Versatile", "Clean"],
  },
  {
    id: "17",
    name: "Komaram Bheem",
    movie: "RRR",
    actor: "NTR Jr",
    image: "/images/characters/ntr-rrr.jpg",
    description:
      "The powerful yet gentle tribal leader combines raw strength with emotional depth. His distinctive style blends traditional tribal elements with practical workwear.",
    style: "Tribal & Authentic",
    lookTags: ["Tribal", "Rugged", "Earthy", "Revolutionary", "Authentic"],
  },
  {
    id: "18",
    name: "Bhanumathi",
    movie: "Fidaa",
    actor: "Sai Pallavi",
    image: "/images/characters/sai-pallavi-fidaa.jpg",
    description:
      "The natural, village belle style of Bhanumathi features traditional sarees, minimal makeup, and an authentic rural charm that celebrates simplicity and grace.",
    style: "Natural & Traditional",
    lookTags: ["Traditional Sarees", "Natural Beauty", "Village Style", "Minimal Jewelry", "Authentic"],
  },
  {
    id: "19",
    name: "Jai",
    movie: "Mirchi",
    actor: "Prabhas",
    image: "/images/characters/prabhas-mirchi.jpg",
    description:
      "The sophisticated, elegant style of Jai features formal attire, refined taste, and a commanding presence that made this character stand out in Telugu cinema.",
    style: "Sophisticated & Elegant",
    lookTags: ["Formal Wear", "Refined", "Elegant", "Sophisticated", "Stylish"],
  },
]

// Add the missing collections export
export const collections: Collection[] = [
  {
    id: "pokiri",
    name: "Pokiri Collection",
    description: "Edgy street style inspired by Mahesh Babu's iconic role",
    image: "/images/collections/pokiri-collection.jpg",
    character: "Pandu",
    movie: "Pokiri",
    products: ["9", "13", "20"],
    style: "Edgy & Street-smart",
  },
  {
    id: "jalsa",
    name: "Jalsa Collection",
    description: "Casual cool vibes from Pawan Kalyan's trendsetting look",
    image: "/images/collections/jalsa-collection.jpg",
    character: "Sanjay Sahu",
    movie: "Jalsa",
    products: ["10", "2", "6"],
    style: "Casual & Cool",
  },
  {
    id: "darling",
    name: "Darling Collection",
    description: "Charming denim styles inspired by Prabhas",
    image: "/images/collections/darling-collection.jpg",
    character: "Prabha",
    movie: "Darling",
    products: ["11", "4", "18"],
    style: "Charming & Casual",
  },
  {
    id: "sita-ramam",
    name: "Sita Ramam Collection",
    description: "Elegant vintage fashion from the period romance",
    image: "/images/characters/mrunal-thakur-sita-ramam-new.jpg",
    character: "Sita Mahalakshmi",
    movie: "Sita Ramam",
    products: ["19", "27", "28", "29"],
    style: "Vintage & Elegant",
  },
  {
    id: "pushpa",
    name: "Pushpa Collection",
    description: "Bold and rugged styles inspired by Allu Arjun",
    image: "/images/products/pushpa-raj-red-floral-shirt.jpg",
    character: "Pushpa Raj",
    movie: "Pushpa: The Rise",
    products: ["1", "23", "24"],
    style: "Rugged & Raw",
  },
  {
    id: "baahubali",
    name: "Baahubali Collection",
    description: "Majestic royal attire inspired by the epic film",
    image: "/images/characters/prabhas-baahubali.jpg",
    character: "Amarendra Baahubali",
    movie: "Baahubali",
    products: ["4", "25", "26"],
    style: "Royal & Majestic",
  },
  {
    id: "arjun-reddy",
    name: "Arjun Reddy Collection",
    description: "Rebellious casual style that defined a generation",
    image: "/images/characters/vijay-deverakonda-arjun-reddy-hd.jpg",
    character: "Arjun Reddy",
    movie: "Arjun Reddy",
    products: ["6", "9", "20"],
    style: "Urban & Rebellious",
  },
  {
    id: "bommarillu",
    name: "Bommarillu Collection",
    description: "Youthful college styles for the modern student",
    image: "/images/characters/siddharth-bommarillu-hd.jpg",
    character: "Siddhu",
    movie: "Bommarillu",
    products: ["12", "18", "10"],
    style: "Youthful & Fresh",
  },
  {
    id: "rrr",
    name: "RRR Komaram Bheem Collection",
    description: "Authentic tribal-inspired looks from the revolutionary character",
    image: "/images/characters/ntr-rrr.jpg",
    character: "Komaram Bheem",
    movie: "RRR",
    products: ["5", "21", "22"],
    style: "Tribal & Authentic",
  },
  {
    id: "fidaa",
    name: "Fidaa Collection",
    description: "Natural village beauty and traditional charm",
    image: "/images/characters/sai-pallavi-fidaa.jpg",
    character: "Bhanumathi",
    movie: "Fidaa",
    products: ["7"],
    style: "Natural & Traditional",
  },
  {
    id: "mirchi",
    name: "Mirchi Collection",
    description: "Sophisticated and elegant style inspired by Prabhas's character",
    image: "/images/characters/prabhas-mirchi.jpg",
    character: "Jai",
    movie: "Mirchi",
    products: ["30"],
    style: "Sophisticated & Elegant",
  },
]

// Add products alias for compatibility
export const products = featuredProducts
